name: Mirror to Client Repo

on:
  push:
    branches:
      - mirror

jobs:
  mirror:
    runs-on: ubuntu-latest
        
    steps:
      - name: Generate GitHub App Token
        id: generate_app_token
        uses: actions/create-github-app-token@v3 
        with:
          app-id: ${{ secrets.GH_APP_ID }} 
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: csiro

      - name: Generate GitHub App Token
        id: generate_app_token_internal
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.GH_APP_ID }} 
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: csiro-internal
          
      - name: Configure Git
        run: |
          git config --global user.email "${{GITHUB.ACTOR}}@users.noreply.github.com"
          git config --global user.name "${{GITHUB.ACTOR}}"
      
      - name: Clone the Client's Repository
        env:
          GH_TOKEN: ${{ steps.generate_app_token.outputs.token }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/csiro/phylocontrol-viz.git client_repo
          cd client_repo
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/csiro/phylocontrol-viz.git
          
      - name: Add Production Repo as Upstream
        working-directory: client_repo
        env:
          GH_TOKEN: ${{ steps.generate_app_token_internal.outputs.token }}
        run: |
          if ! git remote get-url upstream &>/dev/null; then
            git remote add upstream https://x-access-token:${GH_TOKEN}@github.com/csiro-internal/phylocontrol-viz-dev.git
          fi
          git fetch upstream

      - name: Merge Production Changes
        working-directory: client_repo
        run: |
          git checkout prerelease
          git merge upstream/mirror -Xours -s recursive --no-edit --allow-unrelated-histories

      - name: Push Changes to Client Repo
        working-directory: client_repo
        run: git push origin prerelease

